name: Deploy HTML to IIS

on:
  push:
    branches:
      - main

  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:   # optional manual trigger

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy index.html to IIS
        run: |
          Copy-Item -Path "index.html" -Destination "C:\inetpub\wwwroot\index.html" -Force

      - name: Done
        run: echo "Deployment successful"s
