name: Deploy HTML to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy index.html to IIS
        run: |
          Copy-Item -Path "index.html" -Destination "C:\inetpub\wwwroot\index.html" -Force

      - name: Done
        run: echo "Deployment successful"